### ISSUE TITLE
CRT is statically linked on Windows

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/msquic#101]
msquic statically links the CRT on Windows. This is different from how CoreCLR (and other CoreCLR components) link the CRT - they link to UCRT dynamically.

This has three effects:
* msquic.dll is likely a lot bigger than it needs to (we saw 200 kB savings when NativeAOT switched to UCRT a couple weeks back: https://github.com/dotnet/runtime/pull/71182).
* Bigger size means bigger working set impact.
* Security fixes done to the CRT will not be automatically picked up when the OS is serviced

Cc @vitek-karas @sbomer @karelz @wfurt

**Comment by nibanks** [comment]
MsQuic supports dynamic link. If using build.ps1, specify `-DynamicCRT` or if using cmake set `QUIC_STATIC_LINK_CRT=off`.

**Comment by MichalStrehovsky** [comment]
> MsQuic supports dynamic link. If using build.ps1, specify `-DynamicCRT` or if using cmake set `QUIC_STATIC_LINK_CRT=off`.

It might be a bit more work because in the runtime repo we do:

https://github.com/dotnet/runtime/blob/82cfad54504c4a8e236f754b9954aeb413654bf7/eng/native/configurecompiler.cmake#L104-L106

This links dynamically against the OS-supplied UCRT, but avoids the VCRuntime140.dll dependency (that doesn't ship with the OS).

We don't want to introduce a dependency on things that don't ship with the OS.

**Comment by nibanks** [comment]
Would you be able to propose a change to MsQuic to fix this?

**Comment by MichalStrehovsky** [comment]
> Would you be able to propose a change to MsQuic to fix this?

https://github.com/microsoft/msquic/pull/2962

**Comment by karelz** [comment]
Thanks @MichalStrehovsky!
@wfurt @rzikm we should probably get it into 7.0 if at all possible. I assume it will require update to msquic release branch ...

**Comment by ManickaP** [comment]
@rzikm is this fixed? Should we close this?

**Comment by rzikm** [comment]
https://github.com/microsoft/msquic/pull/2962 is merged, so I expect it is. Not sure if it made it in 7.0 though.

**Comment by ManickaP** [comment]
This will get automatically propagated to 8.0 with newer msquic, closing unless there's push back on backport.
