### ISSUE TITLE
Bump version to 9.0

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/msquic#154]
The following needs to be done

- [ ] Bump main to 9.0 in eng/Versions.props --> _in PR_ https://github.com/dotnet/msquic/pull/157
- [x] Update Maestro default channel configuration for main to the `.NET 9` channel
- [x] Update the subscriptions to flow msquic .NET 9 into runtime main.

I also noticed that https://github.com/dotnet/msquic/blob/main/FLOW.md is outdated since there are more branches and different msquic versions now. --> _in PR_ https://github.com/dotnet/msquic/pull/157

Contributes to https://github.com/dotnet/runtime/issues/92502

/cc @dotnet/ncl

**Comment by CarnaViire** [comment]
```
➜ msquic git:(update-to-9.0) darc add-default-channel --channel ".NET 9" --branch refs/heads/main --repo https://github.com/dotnet/msquic
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Non-continuable HTTP 401 error encountered while making request
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.DotNet.DarcLib.HttpRequestManager.ExecuteAsync(Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs:line 86
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Error: Failed to add a new default channel association.
Microsoft.DotNet.DarcLib.DarcAuthenticationFailureException: Failure to authenticate: Response status code does not indicate success: 401 (Unauthorized).
```
Funny that I have rights to remove, but not to add @akoeplinger 😆

**Comment by CarnaViire** [comment]
> Update Maestro default channel configuration for main to the .NET 9 channel

@akoeplinger @ViktorHofer can you help with this please? I don't have the rights (see above). Or am I doing something wrong?

**Comment by ViktorHofer** [comment]
You need to do a `darc authenticate` first.

**Comment by akoeplinger** [comment]
Curious, did removing the default channel actually work without auth or did it just not print an error? 😄

**Comment by CarnaViire** [comment]
It did remove stuff, I checked :D I _think_ I had the auth from before, at least I had darc toked from 2 years ago listed. But maybe addition needs either gh or azdo token as well

**Comment by CarnaViire** [comment]
Subscriptions and channels are cleaned up:

```
➜ ~  darc get-default-channels --source-repo msquic
(5334) https://github.com/dotnet/msquic @ main -> .NET 9
➜ ~  darc get-subscriptions --source-repo msquic
https://github.com/dotnet/msquic (.NET 9) ==> 'https://github.com/dotnet/runtime' ('main')
  - Id: 52be7100-09fc-419e-e3a1-08dbf5a42f57
  - Update Frequency: EveryDay
  - Enabled: True
  - Batchable: True
  - Merge Policies:
    AllChecksSuccessful
      ignoreChecks =
                       [
                         "WIP",
                         "license/cla",
                         "Build Analysis",
                         "runtime-coreclr superpmi-diffs",
                         "runtime-coreclr superpmi-replay",
                         "runtime-coreclr jitstress-isas-avx512",
                         "runtime-libraries enterprise-linux"
                       ]
    NoRequestedChanges
➜ ~
```
