### ISSUE TITLE
msquic doesn't have a release/6.0 subscription even though it has a release/6.0 branch

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/msquic#72]
Should this repo have a subscription so that dotnet/runtime's release/6.0 branch gets updates from msquic release/6.0?

@dotnet/ncl @mmitche

**Comment by mmitche** [comment]
> Should this repo have a subscription so that dotnet/runtime's release/6.0 branch gets updates from msquic release/6.0?
> 
> @dotnet/ncl @mmitche

Probably not. Looks like a test-only dependency. The release/6.0 branch hasn't been updated since November. Probably should move to an RTM version of the SDK though.

**Comment by ViktorHofer** [comment]
Msquic ships as part of the shared framework, even though it isn't exposed.

**Comment by wfurt** [comment]
I'm not sure what that even means @ViktorHofer. This really does not depend on anything from runtime besides basic execution to produce intermediate packages

**Comment by ViktorHofer** [comment]
I mean it the other way around. Dotnet/runtime depends on the transport package but there is currently no subscription that flows bits back in case anything changes in this repo's release/6.0 branch.

**Comment by mmitche** [comment]
Added a subscription and set it to manual update. We don't automatically flow every input dependency to runtime to avoid unnecessary churn.

**Comment by ViktorHofer** [comment]
Perfect. Closing as fixed
